# Generated by Django 4.1.2 on 2022-12-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislikes_percentage',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes_percentage',
            field=models.IntegerField(default=72),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=553286),
        ),
    ]
