# Generated by Django 4.1.2 on 2022-12-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0003_alter_comment_video_alter_video_dislikes_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='dislikes_percentage',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes_percentage',
            field=models.IntegerField(default=93),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=15369),
        ),
    ]
