# Generated by Django 4.1.2 on 2022-12-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0004_video_likes_alter_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=2250),
        ),
    ]
