# Generated by Django 4.1.2 on 2022-12-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0004_remove_comment_video_comment_video_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video_hosting.video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='dislikes_percentage',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes_percentage',
            field=models.IntegerField(default=71),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=683132),
        ),
    ]
