# Generated by Django 4.1.2 on 2022-12-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0005_video_dislikes_alter_video_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=775947),
        ),
    ]
