# Generated by Django 3.2.5 on 2023-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0006_auto_20230127_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislikes_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
