# Generated by Django 4.1.2 on 2022-12-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0006_alter_video_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
        migrations.AddField(
            model_name='video',
            name='dislikes_percentage',
            field=models.IntegerField(default=34),
        ),
        migrations.AddField(
            model_name='video',
            name='likes_percentage',
            field=models.IntegerField(default=75),
        ),
    ]
