# Generated by Django 3.2.5 on 2023-01-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0007_auto_20230127_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='dislikes_percentage',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='likes_percentage',
            new_name='likes',
        ),
    ]
