# Generated by Django 4.1.2 on 2022-12-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0008_video_views_alter_video_dislikes_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislikes_percentage',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes_percentage',
            field=models.IntegerField(default=93),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=338931),
        ),
    ]
