# Generated by Django 4.1.2 on 2022-12-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0012_alter_video_dislikes_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislikes_percentage',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes_percentage',
            field=models.IntegerField(default=84),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=440454),
        ),
    ]
