# Generated by Django 4.1.2 on 2022-12-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0014_alter_video_dislikes_percentage_alter_video_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislikes_percentage',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes_percentage',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=98505),
        ),
    ]
