# Generated by Django 4.1.2 on 2022-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0015_alter_video_dislikes_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='create_at',
        ),
        migrations.AlterField(
            model_name='video',
            name='dislikes_percentage',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=276184),
        ),
    ]
